export const ES = {
  introTitle: 'Ver campaña de recolección de basura',
  location: 'Ubicación',
  homeHeaderSubTitle: 'Campaña de recolección de basura',
  homeHeaderTitle: 'Botadero a cielo abierto',
  allDetails: 'Ver toda la información',
  enrollment: 'Inscribirme en la campaña',
  contactUs: 'Contáctenos',
  helpAlert: 'Ayúdanos a recuperar la zona!',
  address: '150 mts este del Salón Comunal de la Isla de Moravia',
  copy: 'Copiar',
  goBack: 'Regresar',
  hosts: 'Organizadores',
  sebasRole: 'Ingeniero en Computación, Vecino',
  danielRole: 'Ingeniero Ambiental, Contralor Ambiental Municipal de Moravia',
  calendarYourDate: 'Calendariza las fechas',
  inProgress: 'Por definir',
  generalInfo: 'Información',
};
